"use strict";

const { v4 } = require("uuid");
// const getDynanoDB = require("aws-sdk");
const getDynanoDB = require("aws-sdk");

const addTodo = async (event) => {
  const dynomoDB = new getDynanoDB.DynamoDB.DocumentClient();

  const { todo } = JSON.parse(event.body);
  const createdAt = new Date().toLocaleDateString();
  const id = v4();

  console.log("The id is generated by system: " + id);
  const newTodo = {
    id,
    todo,
    createdAt,
    completed: false,
  };

  await dynomoDB.put({
    TableName: "TodoTable",
    Items: newTodo,
  });
  return {
    statusCode: 200,
    body: JSON.stringify(newTodo),
  };
};
module.exports = { handler: addTodo };
